version: '3.8'

services:
    mysql-db:
        image: mysql:8.0.43-debian
        container_name: mysql-db-container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: algafood
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data: